Course work 2024
N1X41/FLT pull request #1
Opened 2024-11-21 19:57 UTC by N1X41

Первое тестирование

2024-12-01 17:42 UTC, TonitaN requested changes
Правим базовую логику, а потом созваниваемся по поводу улучшения стратегии разбора.

2024-12-01 17:42 UTC, TonitaN commented on course_work_fkm/lib/classes/equation.dart
> +    return ((left.length != right.length && left.length * right.length == 0) ||
Почему? Может быть и непустая часть равна пустой, если непустая состоит только из переменных.

2024-12-01 17:42 UTC, TonitaN commented on course_work_fkm/lib/classes/equation.dart
> +        (left[0].toLowerCase() != left[0] &&
Лучше это сделать через обертки isVariable и isLetter

2024-12-01 17:42 UTC, TonitaN commented on course_work_fkm/lib/classes/equation.dart
> +           left[0].toUpperCase() == left[0]) {
А одинаковые переменные не сокращаем?

2024-12-01 17:42 UTC, TonitaN commented on course_work_fkm/lib/classes/equation.dart
> +        if (Set.from(leftSub.split('')..sort()).toString() == Set.from(rightSub.split('')..sort()).toString()) {
Но разбиение может работать и на неравных подстроках. Например, если
`AxBy=xBAy`
Тут `Ax=xB` - подуравнение, но как отсортированные строки они не будут равны.
Вот если по переменным только - да, должны быть равны как отсортированные строки. + добавить равенство по длине обычное, тогда ваш метод будет работать.

2024-12-01 17:42 UTC, TonitaN commented on course_work_fkm/lib/functions/for_graph.dart
> +      if (newNode.equations.every((eq) => eq != equat) &&
А коммутативность равенства не учитывается?

2024-12-01 17:42 UTC, TonitaN commented on course_work_fkm/lib/functions/for_graph.dart
> +      if (newNode.equations.every((eq) => eq != equat) &&
Кстати, логично учесть его прямо в классе уравнения.

2024-12-03 01:26 UTC, N1X41 commented on course_work_fkm/lib/classes/equation.dart
> +        (left[0].toLowerCase() != left[0] &&
fix

2024-12-03 01:30 UTC, N1X41 commented on course_work_fkm/lib/classes/equation.dart
> +    return ((left.length != right.length && left.length * right.length == 0) ||
fix

2024-12-03 01:32 UTC, N1X41 commented on course_work_fkm/lib/classes/equation.dart
> +           left[0].toUpperCase() == left[0]) {
fix

2024-12-03 01:57 UTC, N1X41 commented on course_work_fkm/lib/classes/equation.dart
> +        if (Set.from(leftSub.split('')..sort()).toString() == Set.from(rightSub.split('')..sort()).toString()) {
fix

2024-12-03 02:00 UTC, N1X41 commented on course_work_fkm/lib/functions/for_graph.dart
> +      if (newNode.equations.every((eq) => eq != equat) &&
fix

2024-12-24 21:44 UTC, TonitaN requested changes

2024-12-24 21:44 UTC, TonitaN commented on course_work_fkm/lib/functions/for_nodes.dart
> +    if (equations[i].left != equations[i].right) {
Такие уравнения вообще сразу должны быть упрощены в ноль

2024-12-24 21:44 UTC, TonitaN commented on course_work_fkm/lib/functions/for_nodes.dart
> +      if (equations[i].left.length > equations[i].right.length && _hasVars(equations[i].left)) {
Опять к вопросу о нормальных формах (распределение по длинам частей уравнения)

2024-12-24 21:44 UTC, TonitaN commented on course_work_fkm/lib/functions/for_graph.dart
>    newNode.equations.sort(
Вот сюда и нормализацию в рамках одного уравнения добавить

2024-12-24 21:44 UTC, TonitaN commented on course_work_fkm/lib/functions/for_nodes.dart
> +    Equation maxBenefit = substitution.entries.reduce((a, b) => a.value > b.value ? a : b).key;
По какой метрике самая выгодная?
Метрику, повторюсь, вынести в отдельную функцию

2024-12-25 23:26 UTC, merged